# actri-visualization

In [11]:
import ssl
import numpy as np
import matplotlib
import pandas as pd

In [12]:
##pd settings
pd.set_option('display.max_columns', 100)
##opening databases
land = pd.read_csv("tri_land.csv")
air = pd.read_csv("tri_air.csv")
ug = pd.read_csv("tri_underground1.csv")
water = pd.read_csv("tri_water.csv")

##displaying first 5 rows of each database
land.head(5)
#air.head(5)
#ug.head(5)
#water.head(5)

/usr/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3145: DtypeWarning: Columns (13,31) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
/usr/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3145: DtypeWarning: Columns (31) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,TRI_FACILITY_ID,DOC_CTRL_NUM,FACILITY_NAME,STREET_ADDRESS,CITY_NAME,COUNTY_NAME,STATE_COUNTY_FIPS_CODE,STATE_ABBR,ZIP_CODE,REGION,FAC_CLOSED_IND,ASGN_FEDERAL_IND,ASGN_AGENCY,PARENT_CO_DB_NUM,PARENT_CO_NAME,STANDARDIZED_PARENT_COMPANY,EPA_REGISTRY_ID,TRADE_SECRET_IND,REPORTING_YEAR,ELEMENTAL_METAL_INCLUDED,CAS_NUM,CHEM_NAME,LIST_3350,CARCINOGEN,CLEAN_AIR,PRIMARY_SIC_CODE,SIC_CODES,PRIMARY_NAICS_CODE,NAICS_CODES,INDUSTRY_CODE,ENVIRONMENTAL_MEDIUM,RELEASE_RANGE_CODE,TOTAL_RELEASE,REL_EST_AMT,RELEASE_NA,RELEASE_BASIS_EST_CODE,SRS_ID
0,15025RSTCH400ST,1388025294164,KOPPERS INC CLAIRTON TAR PLANT,300 N STATE ST,CLAIRTON,ALLEGHENY,42003,PA,15025,3,0,C,NaN,196991582,KOPPERS INC,KOPPERS INC,1.100003e+11,0,1988,106-44-5,NaN,P-CRESOL,N,N,Y,2865,2865,325192,325192.0,325,LAND TREA,NaN,NaN,0.0,1,NaN,23606.0
1,15025RSTCH400ST,1388025294164,KOPPERS INC CLAIRTON TAR PLANT,300 N STATE ST,CLAIRTON,ALLEGHENY,42003,PA,15025,3,0,C,NaN,196991582,KOPPERS INC,KOPPERS INC,1.100003e+11,0,1988,106-44-5,NaN,P-CRESOL,N,N,Y,2865,2865,325192,325192.0,325,LANDF8795,NaN,NaN,0.0,1,NaN,23606.0
2,15025RSTCH400ST,1388025294164,KOPPERS INC CLAIRTON TAR PLANT,300 N STATE ST,CLAIRTON,ALLEGHENY,42003,PA,15025,3,0,C,NaN,196991582,KOPPERS INC,KOPPERS INC,1.100003e+11,0,1988,106-44-5,NaN,P-CRESOL,N,N,Y,2865,2865,325192,325192.0,325,OTH DISP,NaN,NaN,0.0,1,NaN,23606.0
3,15025RSTCH400ST,1388025294164,KOPPERS INC CLAIRTON TAR PLANT,300 N STATE ST,CLAIRTON,ALLEGHENY,42003,PA,15025,3,0,C,NaN,196991582,KOPPERS INC,KOPPERS INC,1.100003e+11,0,1988,106-44-5,NaN,P-CRESOL,N,N,Y,2865,2865,325192,325192.0,325,OTH LANDF,NaN,NaN,0.0,0,NaN,23606.0
4,15025RSTCH400ST,1388025294164,KOPPERS INC CLAIRTON TAR PLANT,300 N STATE ST,CLAIRTON,ALLEGHENY,42003,PA,15025,3,0,C,NaN,196991582,KOPPERS INC,KOPPERS INC,1.100003e+11,0,1988,106-44-5,NaN,P-CRESOL,N,N,Y,2865,2865,325192,325192.0,325,RCRA C,NaN,NaN,0.0,0,NaN,23606.0

In [10]:
# Let's try cleaning this up a bit. 
#land.drop(columns=['TRI_FACILITY_ID', 'DOC_CTRL_NUM', 'STATE_COUNTY_FIPS_CODE', 'STATE_ABBR', 'REGION', 'PRIMARY_NAICS_CODE', 'NAICS_CODES', "INDUSTRY_CODE"])
land.drop(columns=[land.columns[0], land.columns[1], land.columns[6], land.columns[7], land.columns[9]
                  , land.columns[10], land.columns[11], land.columns[12], land.columns[13]
                  , land.columns[14], land.columns[16], land.columns[17], land.columns[18], land.columns[19]])

,FACILITY_NAME,STREET_ADDRESS,CITY_NAME,COUNTY_NAME,ZIP_CODE,STANDARDIZED_PARENT_COMPANY,CAS_NUM,CHEM_NAME,LIST_3350,CARCINOGEN,...,PRIMARY_NAICS_CODE,NAICS_CODES,INDUSTRY_CODE,ENVIRONMENTAL_MEDIUM,RELEASE_RANGE_CODE,TOTAL_RELEASE,REL_EST_AMT,RELEASE_NA,RELEASE_BASIS_EST_CODE,SRS_ID
0,KOPPERS INC CLAIRTON TAR PLANT,300 N STATE ST,CLAIRTON,ALLEGHENY,15025,KOPPERS INC,NaN,P-CRESOL,N,N,...,325192,325192.0,325,LAND TREA,NaN,NaN,0.0,1,NaN,23606.0
1,KOPPERS INC CLAIRTON TAR PLANT,300 N STATE ST,CLAIRTON,ALLEGHENY,15025,KOPPERS INC,NaN,P-CRESOL,N,N,...,325192,325192.0,325,LANDF8795,NaN,NaN,0.0,1,NaN,23606.0
2,KOPPERS INC CLAIRTON TAR PLANT,300 N STATE ST,CLAIRTON,ALLEGHENY,15025,KOPPERS INC,NaN,P-CRESOL,N,N,...,325192,325192.0,325,OTH DISP,NaN,NaN,0.0,1,NaN,23606.0
3,KOPPERS INC CLAIRTON TAR PLANT,300 N STATE ST,CLAIRTON,ALLEGHENY,15025,KOPPERS INC,NaN,P-CRESOL,N,N,...,325192,325192.0,325,OTH LANDF,NaN,NaN,0.0,0,NaN,23606.0
4,KOPPERS INC CLAIRTON TAR PLANT,300 N STATE ST,CLAIRTON,ALLEGHENY,15025,KOPPERS INC,NaN,P-CRESOL,N,N,...,325192,325192.0,325,RCRA C,NaN,NaN,0.0,0,NaN,23606.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70266,CHESWICK POWER PLANT,PITTSBURGH & PORTER ST,SPRINGDALE,ALLEGHENY,15144,GENON HOLDINGS INC,NaN,ARSENIC COMPOUNDS,N,N,...,221112,221112.0,2211,OTH DISP,NaN,NaN,0.0,1,NaN,649418.0
70267,CHESWICK POWER PLANT,PITTSBURGH & PORTER ST,SPRINGDALE,ALLEGHENY,15144,GENON HOLDINGS INC,NaN,ARSENIC COMPOUNDS,N,N,...,221112,221112.0,2211,OTH LANDF,NaN,NaN,0.0,1,NaN,649418.0
70268,CHESWICK POWER PLANT,PITTSBURGH & PORTER ST,SPRINGDALE,ALLEGHENY,15144,GENON HOLDINGS INC,NaN,ARSENIC COMPOUNDS,N,N,...,221112,221112.0,2211,RCRA C,NaN,NaN,0.0,1,NaN,649418.0
70269,CHESWICK POWER PLANT,PITTSBURGH & PORTER ST,SPRINGDALE,ALLEGHENY,15144,GENON HOLDINGS INC,NaN,ARSENIC COMPOUNDS,N,N,...,221112,221112.0,2211,SI 5.5.3A,NaN,NaN,0.0,1,NaN,649418.0
70270,CHESWICK POWER PLANT,PITTSBURGH & PORTER ST,SPRINGDALE,ALLEGHENY,15144,GENON HOLDINGS INC,NaN,ARSENIC COMPOUNDS,N,N,...,221112,221112.0,2211,SI 5.5.3B,NaN,NaN,0.0,1,NaN,649418.0