In [15]:
import ssl
import numpy as np
import matplotlib
import pandas as pd

In [16]:
##open air database
air = pd.read_csv("tri_air.csv")

##drops columns that we don't need
air = air.drop(columns=['TRI_FACILITY_ID','DOC_CTRL_NUM', 'STATE_COUNTY_FIPS_CODE', 'STATE_ABBR', 'REGION'
                   , 'FAC_CLOSED_IND', 'ASGN_FEDERAL_IND', 'ASGN_AGENCY', 'PARENT_CO_DB_NUM'
                   , 'PARENT_CO_NAME', 'EPA_REGISTRY_ID', 'TRADE_SECRET_IND', 'ELEMENTAL_METAL_INCLUDED'
                   , 'CAS_NUM', 'LIST_3350', 'PRIMARY_SIC_CODE', 'SIC_CODES', 'PRIMARY_NAICS_CODE'
                   , 'NAICS_CODES', 'INDUSTRY_CODE', 'RELEASE_RANGE_CODE', 'TOTAL_RELEASE'
                   , 'REL_EST_AMT', 'RELEASE_NA', 'RELEASE_BASIS_EST_CODE', 'SRS_ID'])

air.drop(air[air['REPORTING_YEAR'] < 2000].index, inplace = True)

In [19]:
air_grouped = air.groupby('CHEM_NAME').count()
##air_grouped.head(10)
sorted_air = air_grouped.drop(columns = ['FACILITY_NAME','STREET_ADDRESS', 'CITY_NAME', 'COUNTY_NAME', 'ZIP_CODE', 'STANDARDIZED_PARENT_COMPANY', 'REPORTING_YEAR', 'CLEAN_AIR', 'ENVIRONMENTAL_MEDIUM'])
sorted_air.sort_values('CARCINOGEN')

                              CARCINOGEN
CHEM_NAME
SILVER and SILVER COMPOUNDS            2
BENZOYL PEROXIDE                       2
DIETHANOLAMINE                         2
PHOSPHORUS (YELLOW OR WHITE)           2
2,4-DINITROTOLUENE                     2
...                                  ...
1,2,4-TRIMETHYLBENZENE               444
LEAD                                 550
TOLUENE                              672
XYLENE (MIXED ISOMERS)               752
LEAD COMPOUNDS                       808

[131 rows x 1 columns]

In [20]:
##sorted_air = air_grouped.drop(columns = ['FACILITY_NAME','STREET_ADDRESS', 'CITY_NAME', 'COUNTY_NAME', 'ZIP_CODE', 'STANDARDIZED_PARENT_COMPANY', 'REPORTING_YEAR', 'CLEAN_AIR', 'ENVIRONMENTAL_MEDIUM'])
sorted_air.head(10)

                                                   CARCINOGEN
CHEM_NAME
1,2,4-TRIMETHYLBENZENE                                    444
1-BROMO-1-(BROMOMETHYL)-1,3-PROPANEDICARBONITRILE           6
2,4-DIMETHYLPHENOL                                         64
2,4-DINITROPHENOL                                          14
2,4-DINITROTOLUENE                                          2
2,6-DINITROTOLUENE                                          2
2-CHLORO-1,1,1,2-TETRAFLUOROETHANE                         20
2-METHYLPYRIDINE                                           18
2-PHENYLPHENOL                                              2
4,4'-ISOPROPYLIDENEDIPHENOL                                14